apiVersion: apps/v1
kind: Deployment
metadata:
  name: sigo-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sigo-frontend
  template:
    metadata:
      labels:
        app: sigo-frontend
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: sigo-config
        image: docker.io/brunoferreirag/sigo-frontend:latest
        ports:
        - containerPort: 80
          name: sigo-frontend
        resources:
          requests:
            memory: "128Mi"
            cpu: "128m"
          limits:
            memory: "256Mi"
            cpu: "256m"
---
apiVersion: v1
kind: Service
metadata:
  name: sigo-frontend
spec:
  ports:
    - name: sigo-frontend
      protocol: TCP
      port: 80
  selector:
    app: sigo-frontend
    
---
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    dev.okteto.com/generate-host: "true"
  name: sigo-frontend
spec:
  rules:
  - http:
      paths:
        - path: /
          backend:
            serviceName: sigo-frontend
            servicePort: 80
---
